### ISSUE TITLE
Why Positions set to (0,0( in Flux.1

### ISSUE THREAD

**Issue by Oguzhanercan** [Yuanshi9815/OminiControl#12]
Hi, thanks for clear explanation of DiT architectures at the paper. I want to ask a question about your statement:

"the text condition tokens CT have their query and key projections defined in the same way, with all text token positions set to (0, 0) in FLUX.1". 

Do you know the resason or have an idea for that?

**Comment by Yuanshi9815** [comment]
Hi, this positional indexing design for text tokens was implemented by Black Forest Labs.
