### ISSUE TITLE
Will the training script be released?

### ISSUE THREAD

**Issue by XueniLuo** [Yuanshi9815/OminiControl#15]
Thanks for this great work, and I am wondering will you release the training script? 
Also looking forward to the Comfyui version which could support adding other loras and tools.
That would help a lot if it is possible.

**Comment by XueniLuo** [comment]
> Thanks for your kind words. Yes, releasing the training codes is on our TODO list. #7

Really excited to hear this! looking forward to your new release : D

**Comment by Yuanshi9815** [comment]
Training codes are released. Now you can create your own OminiControl model by customizing any control tasks (3D, multi-view, pose-guided, try-on, etc.) with the FLUX model!
