### ISSUE TITLE
do we have any plan for supporting comfyui? 

### ISSUE THREAD

**Issue by Pancat009** [Yuanshi9815/OminiControl#23]
do we have any plan for supporting comfyui?

**Comment by Yuanshi9815** [comment]
Hi @Pancat009,

Due to limited resources and manpower, we are currently focusing on training the 1024 model. 

ComfyUI support is not currently on our to-do list. We welcome community contributions in this area.

**Comment by joanllabata** [comment]
hope @kijai sees this because is too good to miss.

**Comment by Macoron** [comment]
I did a simple wrapper node for ComfyUI node in case you want to test it
https://github.com/Macoron/ComfyUI-Diffusers-OminiControl

**Comment by Yuanshi9815** [comment]
Thank you so much @Macoron! Really appreciate your contribution to creating a ComfyUI wrapper node. We'll update our readme to include this reference.
