### ISSUE TITLE
what's your training dataset?

### ISSUE THREAD

**Issue by Xuan-World** [Yuanshi9815/OminiControl#27]
Excellent work! I wonder what's your training dataset?
It seems you use the  SUBJECT200K made by your team to train subject-driven generation.
But I don't find the description about your training dataset for spacial-control generation.

**Comment by mycfhs** [comment]
Same question

**Comment by Yuanshi9815** [comment]
Training codes are released. Now you can create your own OminiControl model by customizing any control tasks (3D, multi-view, pose-guided, try-on, etc.) with the FLUX model!
