### ISSUE TITLE
adapter for "subject" class 

### ISSUE THREAD

**Issue by happybunny56** [Yuanshi9815/OminiControl#28]
Can you please share adapter for "subject" class? 
pipeline.set_adapters(conditions[0].condition_type)

**Comment by Yuanshi9815** [comment]
Hi! You can find the subject adapter [here](https://huggingface.co/Yuanshi/OminiControl/tree/main/omini).

Please check out`examples/subject.ipynb` in the repository for usage instructions and examples. This notebook demonstrates how to load and use the adapter for subject-driven generation properly.
