### ISSUE TITLE
when will the train codes be available? Looking forward to it!

### ISSUE THREAD

**Issue by xdfeng07** [Yuanshi9815/OminiControl#33]
Hi, current 512 models are really doing a great job, excelling greatly in all kinds of image-editting image-translation tasks. So when will the training code be available? Can't wait to try with our own data for certain specified categories : )

**Comment by xduzhangjiayu** [comment]
+1

**Comment by universewill** [comment]
+1

**Comment by Yuanshi9815** [comment]
Training codes are released. Now you can create your own OminiControl model by customizing any control tasks (3D, multi-view, pose-guided, try-on, etc.) with the FLUX model!

**Comment by universewill** [comment]
> Hi @xdfeng07 @xduzhangjiayu @universewill
> 
> Training codes are released. Now you can create your own OminiControl model by customizing any control tasks (3D, multi-view, pose-guided, try-on, etc.) with the FLUX model!

How much vram needed to train 512x512 and 704x704 with batchsize = 1 ?
