### ISSUE TITLE
what is cond_type_embed ?

### ISSUE THREAD

**Issue by Xuan-World** [Yuanshi9815/OminiControl#38]
Excellent Work! I have a question in your code. 
`if hasattr(self, "cond_type_embed") and condition_type_ids is not None:
        cond_type_proj = self.time_text_embed.time_proj(condition_type_ids[0])
        cond_type_emb = self.cond_type_embed(cond_type_proj.to(dtype=cond_temb.dtype))
        cond_temb = cond_temb + cond_type_emb`
What is the function of this code? I suppose it doesn't work in this version of your code, but I wonder why you didn't use it to train your network? And if this part of code is not been executed, the Variable 'condition_type_ids' is redundant in your code. I wonder whether you validate the effect of this type of design?

**Comment by Yuanshi9815** [comment]
Hi @Xuan-World !

This module was designed for an "all-in-one" adapter approach, which would allow multiple control types to be handled by a single adapter. While it's a functional design and we've seen promising results with it, we haven't released this version yet.
