### ISSUE TITLE
Question about Attention Mask

### ISSUE THREAD

**Issue by sd0809** [Yuanshi9815/OminiControl#41]
Thank you for your wonderful work! 

I have a question regarding the attention mask. In your paper, you mention using BiasedAttention for the interaction between the noisy image and the cond image. However, when I run your code, I've noticed that the attention mask is not being used (by the way, it seems that the attention mask defined in the block/attn_forward function differs slightly from what you mentioned in your paper), and yet it achieves excellent generation results. 

I would like to know if the attention mask is ineffective because I haven't run omini control correctly, or if your current version does not enable the attention mask. Looking forward to your reply, and once again, thank you for providing such an impressive work!

**Comment by Yuanshi9815** [comment]
Hi @sd0809 ,

The BiasedAttention functionality can be activated during inference by passing the `condition_scale` parameter to the `generate()` function. 

Feel free to let us know if you need any clarification about the implementation details.
