### ISSUE TITLE
Query about 1024 Training

### ISSUE THREAD

**Issue by yujiaxu13** [Yuanshi9815/OminiControl#44]
When the subject_1024_beta, did you train it on 1024x1024 images, or simply enlarge the dataset?

**Comment by Yuanshi9815** [comment]
Hi @yujiaxu13,

The `1024_beta` model is available [here](https://huggingface.co/Yuanshi/OminiControl/tree/main/omini).

For proper usage, please follow the [demo code](https://huggingface.co/spaces/Yuanshi/OminiControl/blob/main/src/generate.py) on Huggingface Space:

1. Use reference images with size `(512, 512)`
2. Adjust the `generate()` function code as follows:
   ```python
   if condition.condition_type == "subject":
       delta = 32 if height == 512 else -32
       condition_ids[:, 2] += delta
    ```
Regarding your question about training, yes, we trained the 1024 model on 1024x1024 images specifically. We'll soon release this high-resolution training dataset as a supplement to Subjects200K.

**Comment by Yuanshi9815** [comment]
Training codes are released. Now you can create your own OminiControl model by customizing any control tasks (3D, multi-view, pose-guided, try-on, etc.) with the FLUX model!

**Comment by llcc343** [comment]
> Hi [@yujiaxu13](https://github.com/yujiaxu13),
> 
> The `1024_beta` model is available [here](https://huggingface.co/Yuanshi/OminiControl/tree/main/omini).
> 
> For proper usage, please follow the [demo code](https://huggingface.co/spaces/Yuanshi/OminiControl/blob/main/src/generate.py) on Huggingface Space:
> 
> 1. Use reference images with size `(512, 512)`
> 2. Adjust the `generate()` function code as follows:
>    if condition.condition_type == "subject":
>        delta = 32 if height == 512 else -32
>        condition_ids[:, 2] += delta
> 
> Regarding your question about training, yes, we trained the 1024 model on 1024x1024 images specifically. We'll soon release this high-resolution training dataset as a supplement to Subjects200K.

Why should the  reference images should be 512x512, seems that 1024x1024 could also work
