### ISSUE TITLE
Question about the larger dataset

### ISSUE THREAD

**Issue by DexiangHong** [Yuanshi9815/OminiControl#45]
![img_v3_02he_3a89fed3-41e9-4df6-9d7d-6d8abc034c8g](https://github.com/user-attachments/assets/a9eaa4f0-f321-414a-a7a2-e02a62cd2bf2)
Hi！ What is the approximate size of this larger data set? Was it also generated using flux?

**Comment by Yuanshi9815** [comment]
Hi @DexiangHong,

Yes, all these datasets were generated using Flux and from our [Subjects200K](https://huggingface.co/datasets/Yuanshi/Subjects200K) dataset.

Here's a breakdown of our different models and their training data:
- The model `experimental/subject_512` was trained on a subset of Subjects200K
- The model `omini/subject_512` was trained on the full Subjects200K (both collection 1 and collection2)
- For `subject_1024`, we built a new dataset of high-resolution images using the same pipeline as the 512 datasets. This high-resolution dataset will be released as a supplementary collection to Subjects200K.

Additionally, we minimize the fine-tuned modules in `omini/subject_512` and `omini/subject_1024` - they have fewer modules compared to the experimental version, but they actually have a larger parameter count (increased from 15M to 25M).

Let me know if you have any other questions!

**Comment by DexiangHong** [comment]
Thank you!
