### ISSUE TITLE
Subject driven inpaint

### ISSUE THREAD

**Issue by hamzaakyildiz** [Yuanshi9815/OminiControl#49]
do you have any plan on releasing an inpaint version for subject driven generation. Ultimately, i want to insert an object into my image where the position and scale provided by the mask. I think, there is no need for a new model as the inpaint pipeline can be inferred from text2image pipeline

**Comment by hamzaakyildiz** [comment]
do you have any plan on this ?

**Comment by Yuanshi9815** [comment]
Hi @hamzaakyildiz ,

Thank you for being so interested! This idea aligns with part of our ongoing work. And we have been working on this for quite some time. We will release our work when it's ready! 🙌

**Comment by KleinXin** [comment]
> Hi [@hamzaakyildiz](https://github.com/hamzaakyildiz) ,
> 
> Thank you for being so interested! This idea aligns with part of our ongoing work. And we have been working on this for quite some time. We will release our work when it's ready! 🙌

Is it ready?
I found this idea appeared in FIgure 8 of OminiControl2 paper. 
However, user guide has not been found.
