### ISSUE TITLE
great work ！！ when are you gonna release the train code ?

### ISSUE THREAD

**Issue by tnickMoxuan** [Yuanshi9815/OminiControl#50]

**Comment by Yuanshi9815** [comment]
Hi @tnickMoxuan ,

We are in the final stages of optimizing our training code for public release, and we plan to make it available very soon.

**Comment by Yuanshi9815** [comment]
Hi @tnickMoxuan ,

Training codes are released. Now you can create your own OminiControl model by customizing any control tasks (3D, multi-view, pose-guided, try-on, etc.) with the FLUX model!
