### ISSUE TITLE
Only Norm, MM Attention Fine-tuned with LoRA, Not MLP, Out Projection

### ISSUE THREAD

**Issue by GloryyrolG** [Yuanshi9815/OminiControl#52]
Hi @Yuanshi9815 @sleeper @ManishSahu53 et. al.,

thx for ur great work! may i ask if trainable modules are different from the illustration in fig. 2? thx & best,

![image](https://github.com/user-attachments/assets/a0ee6eb8-ce10-4d9f-85ac-3d405ca51f87)

**Comment by GloryyrolG** [comment]
Hi @Yuanshi9815 ,

may i check if the rest is not fine-tuned at all? thx & merry xmas,

**Comment by Yuanshi9815** [comment]
Hi @GloryyrolG! 

Thanks for your interest and Christmas wishes! 🎄

The experiments in our paper used the models in the `experimental` folder with full parameter fine-tuning. However, for the models in the `omini` folder, we've switched to a more efficient approach using partial parameter tuning through LoRA.

**Comment by GloryyrolG** [comment]
appreciate & thx for ur clarifications!
