### ISSUE TITLE
LoRA scale=0.0 for non-Conditional tokens

### ISSUE THREAD

**Issue by reallyigor** [Yuanshi9815/OminiControl#53]
Hello @Yuanshi9815 !
Great work!

I have a question regarding setting lora weight for non-conditional tokens to 0.0
See #3 
Can you please mention where you do it in the code? In which module?

Kind regards,
Igor

**Comment by Yuanshi9815** [comment]
Hiii @reallyigor ,

Thanks for your attention. 

You may find it in the file `src/lora_controller.py`. 🙌

**Comment by reallyigor** [comment]
Thank you for such a swift answer!
can you please tell me the exact row?

e.g. `set_lora_scale` function is not used in the code at all

**Comment by Yuanshi9815** [comment]
Hi @reallyigor ,

Merry Christmas! 🎄

The LoRA weight control is implemented through the `enable_lora` context manager. For example, in `src/transformer.py ` line 98:
  ```python
  with enable_lora((self.x_embedder,), model_config.get("latent_lora", False)):
      hidden_states = self.x_embedder(hidden_states)
  ```
When`latent_lora` is `False`, the LoRA weights are set to 0 for the `x_embedder` module.

**Comment by reallyigor** [comment]
Thank you very much, @Yuanshi9815 !
How this `model_config` controls conditional/non-conditional tokens? it enables/disables lora for the whole model, doesnt it?

**Comment by Yuanshi9815** [comment]
Hi @reallyigor ,

We dynamically enable/disable LoRA during model execution. The `model_config` doesn't determine conditional/non-conditional tokens - it only controls whether to use LoRA on non-conditional tokens, which should match the training configuration. 

In our released models, LoRA is used on conditional tokens but not on non-conditional tokens, hence the default False setting.

XD

**Comment by reallyigor** [comment]
Thank you!

**Comment by garychan22** [comment]
hi, since the learned lora is only for conditional tokens, how can we load another lora only for non-conditional tokens with enable_lora? thanks

**Comment by Feynman1999** [comment]
> Hi [@reallyigor](https://github.com/reallyigor) ,
> 
> Merry Christmas! 🎄
> 
> The LoRA weight control is implemented through the `enable_lora` context manager. For example, in `src/transformer.py ` line 98:
> 
> with enable_lora((self.x_embedder,), model_config.get("latent_lora", False)):
>     hidden_states = self.x_embedder(hidden_states)
> When`latent_lora` is `False`, the LoRA weights are set to 0 for the `x_embedder` module.

why you only add lora to condition stream( not with noise or text)，have you compared the results?
