### ISSUE TITLE
How can I use an existing Flux installation with this?

### ISSUE THREAD

**Issue by EightiesPower** [Yuanshi9815/OminiControl#6]
Smoothbrain here, how do I modify the code to make it use an existing Flux installation? I'd rather not download another 30+ gbs of models when I already have them. Thank you.

**Comment by Yuanshi9815** [comment]
Our implementation is based on the official Flux diffusers model. If you already have Flux installed, you only need to download our additional model weights which are relatively small (30-50MB).
