### ISSUE TITLE
Is there any plan to release fine-tune code?

### ISSUE THREAD

**Issue by JoshonSmith** [Yuanshi9815/OminiControl#7]
great work !

**Comment by Yuanshi9815** [comment]
Thanks for your kind words! Yes, releasing the training codes is on our TODO list.

**Comment by JoshonSmith** [comment]
> Thanks for your kind words! Yes, releasing the training codes is on our TODO list.

👍🏻

**Comment by Oguzhanercan** [comment]
@Yuanshi9815 hi, when are you gonna release the train code ?
