### ISSUE TITLE
requirements.txt ..are not perfect

### ISSUE THREAD

**Issue by lior007** [Yuanshi9815/OminiControl#8]
1. The following commands are missing:

pip install gradio
pip install jupyter

if you use gpu cuda
pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu118

2. in the md readme
title 3 promt **and** title 4 promt are the **same**
Prompt3: In a Bauhaus style room, this item is placed on a shiny glass table, with a vase of flowers next to it. In the afternoon sun, the shadows of the blinds are cast on the wall.
Prompt4: In a Bauhaus style room, this item is placed on a shiny glass table, with a vase of flowers next to it. In the afternoon sun, the shadows of the blinds are cast on the wall.

3. There are no clear instructions to start the Gradio interface
**python gradio_app.py**

4. There are no clear instructions to start the notebook
**jupyter notebook**

**Comment by Yuanshi9815** [comment]
Thanks for your detailed feedback! We'll update the documentation to address these.

**Comment by lior007** [comment]
> Thanks for your detailed feedback! We'll update the documentation to address these.

thank you
